server:
    port: 8070

spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/order-db
        username: nibras
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

# API-Gateway url instead of direct service url - for better scalability
application:
    config:
        customer-url: http://localhost:8090/api/v1/customers
        product-url: http://localhost:8050/api/v1/products
        payment-url: http://localhost:8060/api/v1/payments