services:
    postgres:
        container_name: ms_postgresql
        image: postgres
        environment:
            POSTGRES_USER: nibras
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - 5433:5432
        networks:
            - microservices-network
        restart: unless-stopped

    pgadmin:
        container_name: ms_pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - microservices-network
        restart: unless-stopped
        depends_on:
            - postgres

    mongodb:
        container_name: ms_mongo_db
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongo:/data
        environment:
            MONGO_INITDB_ROOT_USERNAME: nibras
            MONGO_INITDB_ROOT_PASSWORD: password

    mongo-express:
        container_name: ms_mongo_express
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: nibras
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_BASICAUTH_USERNAME: nibras
            ME_CONFIG_BASICAUTH_PASSWORD: password
        restart: unless-stopped
        depends_on:
            - mongodb

    zookeeper:
        container_name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "22181:2181"
        networks:
            - microservices-network
    kafka:
        container_name: ms_kafka
        image: confluentinc/cp-kafka:latest
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        networks:
            - microservices-network

    mail-dev:
        container_name: ms_mail_dev
        image: maildev/maildev
        ports:
            - 1080:1080
            - 1025:1025

networks:
    microservices-network:
        driver: bridge

volumes:
    postgres:
    pgadmin:
    mongo:
